### ISSUE TITLE
Post for Pixls.us

### ISSUE THREAD

**Issue by REMC19** [ktgw0316/LightZone-backup#24]
Masahiro
Do you mind if I add a post on the Pixls.us forum, just to let people know that despite the fact that the website is down, the project is still being actively being developed, that the program can be downloaded from here, and that people can let you know of problems or suggestions via the issues tab.
Its just that with the site down nobody knows that you are there working away on the program, and that they can still download it.
Thank you for getting in touch after my initial posts by the way.

**Comment by REMC19** [comment]
Hi Masahiro
Would I be correct in thinking that the fact you self assigned this issue means that you intend to do a post yourself at PIXLS.US
If you do, note that the main guy there is patdavid, and the way their forum works you can message him privately (or any other user) in addition to making public posts.
I think there are quite a few developers knocking about on there, and they seem to be quite open about bouncing ideas of each other and lending a hand where they can.
I have already asked patdavid if he could update the LightZone link on the software page as it still links to the LightZone.org site that’s down at the minute (he intends to sort the link in the next day or two I believe).
In his reply telling me that, he also mentioned that they have helped various other projects with website related issues and would be happy to help with anything they could in that direction as well.

**Comment by ktgw0316** [comment]
@REMC19 Thank you for the info. I'll post on the PIXLS.US in this weekend -- I'm bit busy these days, plus, it took me a long time to writing something in English (at least longer than writing source code).

**Comment by ktgw0316** [comment]
Done in https://github.com/ktgw0316/LightZone/discussions/31#discussioncomment-4369634. Let's continue the discussion there and/or at the PIXLS.US forum.
