### ISSUE TITLE
4.2.5 Windows Version

### ISSUE THREAD

**Issue by REMC19** [ktgw0316/LightZone-backup#26]
Masahiro
Would it be possible to have a 4.2.5 WINDOWS version of the program.
_I don't mean for any actual program changes - there is one reason behind my request._
With things the way they are with the site I think it needs to be made as easy as possible to download the program - and if you click on latest then you are only presented with the Mac version of the program.
You have to go looking to find the Windows version to be able to download it, and some people will not bother (or just won't be able to find it).
Hope you think this is a reasonable idea.

**Comment by sfink16** [comment]
Please see --> https://github.com/ktgw0316/LightZone/releases/tag/4.2.5
This is a bug-fix release only for macOS. For Windows and Linux, please use [4.2.4](https://github.com/ktgw0316/LightZone/releases/tag/4.2.4) instead.

**Comment by ktgw0316** [comment]
@sfink16 I've added the "For Windows and Linux ..." comment today, only a few minutes before you noticed it. :)

@REMC19 That comment solves this issue, right?

**Comment by REMC19** [comment]
Looks good to me - it takes you straight to the correct version for Windows and Linux and you can see the file(s) you need to download. So I'd say the issue is now solved.
Basically, I was just trying to make things as easy as possible for anybody interested in downloading the program.
